# Generated by Django 4.1.3 on 2022-11-17 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenDetail',
            fields=[
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerDetail',
            fields=[
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('section', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerDetail',
            fields=[
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.managerdetail')),
            ],
        ),
    ]
